### ISSUE TITLE
Compile error when using with Shield.

### ISSUE THREAD

**Issue by wess** [mustafaturan/authable#18]
==> authable
Compiling 34 files (.ex)

== Compilation error on file lib/authable/grant_types/base.ex ==
** (CompileError) lib/authable/grant_types/base.ex:83: nil.__struct__/1 is undefined, cannot expand struct nil
    (stdlib) lists.erl:1354: :lists.mapfoldl/3

could not compile dependency :authable, "mix compile" failed. You can recompile this dependency with "mix deps.compile authable", update it with "mix deps.update authable" or clean it with "mix deps.clean authable"
make: *** [run] Error 1

**Comment by mustafaturan** [comment]
Hi @wess ,

Which versions are you using for both the authable and shield packages?

**Comment by wess** [comment]
@mustafaturan - Thanks for the fast response, currently Im using (as in my mix.exs) just: 
`{:shield, "~> 0.6.0"}` Here is my deps:

```
{:phoenix, "~> 1.2.1"},
{:phoenix_pubsub, "~> 1.0"},
{:phoenix_ecto, "~> 3.0"},
{:postgrex, ">= 0.0.0"},
{:gettext, "~> 0.11"},
{:cowboy, "~> 1.0"},
{:comeonin, "~> 3.0"},
{:shield, "~> 0.6.0"},
```

**Comment by mustafaturan** [comment]
I would recommend deleting mix.lock and try again, if it does not work let me know.

I just created a sample app with the deps below, it worked without any problem.

```
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.1.2", override: true},
     {:shield, "~> 0.6.0"}]
```

**Comment by mustafaturan** [comment]
Also be sure that correctly applied all steps of installation from scratch on the [shield/README.md](https://github.com/mustafaturan/shield/blob/master/README.md).

**Comment by wess** [comment]
I removed the lock, followed the steps: https://gist.github.com/wess/e6083c09509ff9fb3967edd4fe7778db

What version of Elixir are you using?

**Comment by mustafaturan** [comment]
Most probably, you forgot to set a config : `Application.get_env(:authable, :token_store)`

**Comment by mustafaturan** [comment]
Elixir 1.4

**Comment by mustafaturan** [comment]
Do you have the following DB config values for `Authable` on your `dev.exs`, `test.exs` and `prod.exs`

```
config :authable, Authable.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgress",
  password: "postgress",
  database: "blog3_dev",
  hostname: "localhost",
  pool_size: 10
```

**Comment by wess** [comment]
Ahh, forgot the db stuff. Thanks for working that out with me!
