### ISSUE TITLE
Scopes cannot be configured

### ISSUE THREAD

**Issue by tpitale** [mustafaturan/authable#30]
My config includes:

```ex
…
scopes: ~w(factory)
…
```

But `Authable.GrantType.ClientCredentials` has `@scopes` as `read, write, session`

So when I try to `Authable.OAuth2.authorize` with client credentials and a scope of "factory", I always get an `invalid_scopes` error:

```
{:error,
 %{invalid_scope: "Allowed scopes for the token are read, write, session."},
 :bad_request}
```

I have tried to clean and compile again.

If I run `iex -S mix` and then `Enum.join(Application.get_env(:authable, :scopes), ",")`, I get "factory". But that does not appears to be what the grant type has in `@scopes`.

**Comment by mustafaturan** [comment]
`@` char makes a hard cache in elixir lang.
You need to delete the `/_build` folder to see your scopes are working properly after you change the config. If it does not work, let me know.

**Comment by tpitale** [comment]
Ah, I though `mix clean` would clear up that folder. Trying now.

**Comment by tpitale** [comment]
That works, thanks.
