### ISSUE TITLE
Support for never-expiring tokens

### ISSUE THREAD

**Issue by tpitale** [mustafaturan/authable#31]
In other worlds (ruby's devise comes to mind) one can create "app" tokens that never expire. This is a useful feature when you want similar auth mixed for both users and other services consuming an API.

If this is something you'd be open to supporting I can try to send a PR.

Right now, I'm trying to set the `expires_at` to be far future, which doesn't work great with integer-based timestamps in postgres `expected an integer in -2147483648..2147483647, got 4651512186`. 😛

Thanks!

**Comment by mustafaturan** [comment]
Max int for `postgres` is `2147483647` which is `GMT: Tuesday, 19 January 2038 03:14:07`

WDYT?

**Comment by tpitale** [comment]
Yeah I used a 10 year expiry … that'll do for now. Just thought I'd bring it up.
