### ISSUE TITLE
Clarification in README on replacing Authable.Repo with our own repo

### ISSUE THREAD

**Issue by tpitale** [mustafaturan/authable#34]
There's a line in the README that suggests replacing `Authable.Repo` with our own repo. Could you clarify what is meant by this.

Is it, we should change config to `MyApp.Repo` wherever the examples show `Authable.Repo`?

Or is it something else?

**Comment by tpitale** [comment]
I would normally ask this on Stackoverflow or something, but wanted to get an answer so I could send a PR with README changes.

**Comment by tpitale** [comment]
It seems like `ecto_repos` config isn't used in Authable?

It also seems like we have to have `Authable.Repo` configured because the project attempts to start/supervisor that Repo.

Would you be open to a PR that allows using an already-configured `Repo`?

**Comment by tpitale** [comment]
In `master` though (not in the released hex package) it no longer appears to be the case that `Authable.Repo` gets supervised by Authable.

Maybe just a new hex package release?

**Comment by tpitale** [comment]
Nope, I was just stuck on some dependencies.

So, yeah. It seems like `ecto_repos` isn't needed and the configured repo can be `Myapp.Repo`. Would you like a PR for the README?

**Comment by mustafaturan** [comment]
With the 0.9.x version, I removed the `Authable.Repo` with incoming requests from the community. You can copy `Authable.Repo` from [test folder](https://github.com/mustafaturan/authable/blob/master/test/support/repo.ex) to your lib folder, this will solve the problem. 

But the idea is to create your own repo, I assume that you already have a repo on your project, if you do not, you can copy it from test folder to your lib folder. 

Pull requests are welcome.
