### ISSUE TITLE
Running migrations of Authable without Authable.Repo

### ISSUE THREAD

**Issue by tpitale** [mustafaturan/authable#36]
If configured as described in the README, there is no `Authable.Repo` and so all of the migrations under that module do not seem to run. Using `mix echo.migrate -r Authable.Repo` results in `** (Mix) Could not load Authable.Repo, error: :nofile. Please configure your app accordingly or pass a repo with the -r option.`

How should these migrations be run?

**Comment by tpitale** [comment]
Config looks like:

```ex
config :authable,
  # ecto_repos: [MyApp.Repo],
  repo: MyApp.Repo,
  resource_owner: Authable.Model.User,
  token_store: Authable.Model.Token,
  client: Authable.Model.Client,
  app: Authable.Model.App
…
```

**Comment by mustafaturan** [comment]
You should use your own repo name as specified in `README.md`

In your case `mix echo.migrate -r MyApp.Repo`

Make sure you copied the migrations from `priv` folder to your app's `priv` folder.

**Comment by tpitale** [comment]
The README should probably mention that copying from package `priv` to app `priv` is now required. Would you like a PR @mustafaturan?

**Comment by mustafaturan** [comment]
Yes, that would be nice 👍
